-- Verification System Migration SQL Reference
-- This file shows the SQL that will be generated by Prisma migrate
-- Run: npx prisma migrate dev --name add_verification_system

-- ============================================================================
-- 1. Add verification fields to Product table
-- ============================================================================

ALTER TABLE "Product"
ADD COLUMN "verification_level" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "verification_badges" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "verification_score" DOUBLE PRECISION;

CREATE INDEX "Product_verification_level_idx" ON "Product"("verification_level");

-- ============================================================================
-- 2. Add verifier fields to User table
-- ============================================================================

ALTER TABLE "User"
ADD COLUMN "role" TEXT NOT NULL DEFAULT 'user',
ADD COLUMN "verifier_stats" JSONB;

CREATE INDEX "User_role_idx" ON "User"("role");

-- ============================================================================
-- 3. Create VerificationStatus enum
-- ============================================================================

CREATE TYPE "VerificationStatus" AS ENUM (
  'PENDING',
  'ASSIGNED',
  'IN_PROGRESS',
  'COMPLETED',
  'APPROVED',
  'REJECTED',
  'CANCELLED'
);

-- ============================================================================
-- 4. Create Verification table
-- ============================================================================

CREATE TABLE "Verification" (
  "id" TEXT NOT NULL,
  "product_id" TEXT NOT NULL,
  "verifier_id" TEXT,

  -- Verification details
  "level" INTEGER NOT NULL,
  "status" "VerificationStatus" NOT NULL DEFAULT 'PENDING',

  -- Pricing
  "fee" INTEGER NOT NULL,
  "platform_share" INTEGER NOT NULL,
  "verifier_share" INTEGER NOT NULL,

  -- Report
  "report" JSONB,
  "score" DOUBLE PRECISION,

  -- Badges
  "badges" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],

  -- Workflow timestamps
  "requested_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "assigned_at" TIMESTAMP(3),
  "reviewed_at" TIMESTAMP(3),
  "completed_at" TIMESTAMP(3),

  CONSTRAINT "Verification_pkey" PRIMARY KEY ("id")
);

-- Foreign keys
ALTER TABLE "Verification"
ADD CONSTRAINT "Verification_product_id_fkey"
FOREIGN KEY ("product_id") REFERENCES "Product"("id")
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Verification"
ADD CONSTRAINT "Verification_verifier_id_fkey"
FOREIGN KEY ("verifier_id") REFERENCES "User"("id")
ON DELETE SET NULL ON UPDATE CASCADE;

-- Indexes
CREATE INDEX "Verification_product_id_idx" ON "Verification"("product_id");
CREATE INDEX "Verification_verifier_id_idx" ON "Verification"("verifier_id");
CREATE INDEX "Verification_status_idx" ON "Verification"("status");
CREATE INDEX "Verification_level_idx" ON "Verification"("level");
CREATE INDEX "Verification_completed_at_idx" ON "Verification"("completed_at");

-- ============================================================================
-- 5. Create PayoutStatus enum
-- ============================================================================

CREATE TYPE "PayoutStatus" AS ENUM (
  'PENDING',
  'INCLUDED_IN_SETTLEMENT',
  'PAID'
);

-- ============================================================================
-- 6. Create VerifierPayout table
-- ============================================================================

CREATE TABLE "VerifierPayout" (
  "id" TEXT NOT NULL,
  "verifier_id" TEXT NOT NULL,
  "verification_id" TEXT NOT NULL,
  "settlement_id" TEXT,

  "amount" INTEGER NOT NULL,
  "status" "PayoutStatus" NOT NULL DEFAULT 'PENDING',

  "paid_at" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "VerifierPayout_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "VerifierPayout_verification_id_key" UNIQUE ("verification_id")
);

-- Foreign keys
ALTER TABLE "VerifierPayout"
ADD CONSTRAINT "VerifierPayout_verifier_id_fkey"
FOREIGN KEY ("verifier_id") REFERENCES "User"("id")
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "VerifierPayout"
ADD CONSTRAINT "VerifierPayout_verification_id_fkey"
FOREIGN KEY ("verification_id") REFERENCES "Verification"("id")
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "VerifierPayout"
ADD CONSTRAINT "VerifierPayout_settlement_id_fkey"
FOREIGN KEY ("settlement_id") REFERENCES "Settlement"("id")
ON DELETE SET NULL ON UPDATE CASCADE;

-- Indexes
CREATE INDEX "VerifierPayout_verifier_id_idx" ON "VerifierPayout"("verifier_id");
CREATE INDEX "VerifierPayout_verification_id_idx" ON "VerifierPayout"("verification_id");
CREATE INDEX "VerifierPayout_settlement_id_idx" ON "VerifierPayout"("settlement_id");
CREATE INDEX "VerifierPayout_status_idx" ON "VerifierPayout"("status");
CREATE INDEX "VerifierPayout_createdAt_idx" ON "VerifierPayout"("createdAt");

-- ============================================================================
-- 7. Update Settlement table
-- ============================================================================

ALTER TABLE "Settlement"
ADD COLUMN "verification_earnings" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "verification_count" INTEGER NOT NULL DEFAULT 0;

-- Add unique constraint for seller_id + period_start
ALTER TABLE "Settlement"
ADD CONSTRAINT "Settlement_seller_id_period_start_key"
UNIQUE ("seller_id", "period_start");

-- ============================================================================
-- 8. Seed initial verifier users (optional)
-- ============================================================================

-- Example: Create a test verifier account
-- INSERT INTO "User" (
--   "id",
--   "email",
--   "name",
--   "role",
--   "emailVerified",
--   "verifier_stats",
--   "createdAt",
--   "updatedAt"
-- ) VALUES (
--   'verifier_test_001',
--   'verifier@example.com',
--   'Test Verifier',
--   'verifier',
--   true,
--   '{"total_verifications": 0, "total_earnings": 0, "approval_rate": 0, "avg_score": 0}',
--   CURRENT_TIMESTAMP,
--   CURRENT_TIMESTAMP
-- );

-- ============================================================================
-- Rollback (if needed)
-- ============================================================================

-- DROP TABLE IF EXISTS "VerifierPayout" CASCADE;
-- DROP TABLE IF EXISTS "Verification" CASCADE;
-- DROP TYPE IF EXISTS "VerificationStatus";
-- DROP TYPE IF EXISTS "PayoutStatus";
-- ALTER TABLE "Product" DROP COLUMN IF EXISTS "verification_level";
-- ALTER TABLE "Product" DROP COLUMN IF EXISTS "verification_badges";
-- ALTER TABLE "Product" DROP COLUMN IF EXISTS "verification_score";
-- ALTER TABLE "User" DROP COLUMN IF EXISTS "role";
-- ALTER TABLE "User" DROP COLUMN IF EXISTS "verifier_stats";
-- ALTER TABLE "Settlement" DROP COLUMN IF EXISTS "verification_earnings";
-- ALTER TABLE "Settlement" DROP COLUMN IF EXISTS "verification_count";
